### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by kailynw**
`python3 manage.py runserver`

>http://localhost:8000/problems

*IDK you might have to install a package or 2 with 'pip3'

### CODE REVIEW

**Comment by grunklejp** [comment]
I'm having issues running the server because of package conflicts. Are you using a python virtualenv? if you are just start up your environment then go `pip freeze > requirements.txt` this'll dump all of the pip modules and their versions for that virtual environment into a text file. So then when I clone the repo all I have to do is create a new virtualenv and type `pip install -r requirements.txt` and it guarantees that we're running with the same dependencies. 

(also we need to put ds store in git ignore)

**Comment by kailynw** [comment]
Okay done

**Comment by grunklejp** [comment]
Did you set everything up in a new virtualenv? it seems like there are a lot of stuff in the requirements that we don't need for the project. Basically when you set up the project using a virtualenv it gives you a blank module library so we can develop using just the bare minimal amount of dependencies. 


### How to set up a virtualenv:
_for anyone who might need it._

1. Install virtualenv
`sudo pip install virtualenv`

2. Make a folder to store virtual environments
`mkdir ~/virtualenvironments`

3. Create new virtual environment
`virtualenv ~/virtualenvironments/insertprojectnamehere`

4. Activate a virtual environment
`source ~/virtualenvironments/insertprojectnamehere/bin/activate`

5. To exit virtualenv
`deactivate`

**Comment by kailynw** [comment]
No everything is local

**Comment by kailynw** [comment]
And okay I’ll set it up later

**Comment by grunklejp** [comment]
Do you want me to push a bare django project with the minimal requirements set up? Then you can just merge your changes into it?

**Comment by kailynw** [comment]
Yea lets do that please.

**Comment by abohlman** [comment]
comment

**Pull request closed without merging**
